#!/bin/sh

set -e
set -u
if [ -n "${V+x}" ]
then
	set -x
fi

timeout=${FD_CLI_TIMEOUT:-1}

# the following trick checks if the variable is set. we can't test if it is
# empty, because the set -u will trigger an error
if [ -z "${FIRMWARED_SOCKET_PATH+x}" ]
then
	socket="/var/run/firmwared.sock"
else
	socket=${FIRMWARED_SOCKET_PATH}
fi

seq_num=$$

pomp_cmd="pomp-cli --timeout ${timeout} --dump --wait ${seq_num} unix:${socket}"

command=$(echo $1 | tr '[a-z]' '[A-Z]')

case "${command}" in
	PING)
		format="%s"
		args=""
		;;
	FOLDERS)
		format="%s"
		args=""
		;;
	LIST)
		format="%s%s"
		folder=$2
		args="${folder}"
		;;
	SHOW)
		format="%s%s%s"
		folder=$2
		identifier=$3
		args="${folder} ${identifier}"
		;;
	DROP)
		format="%s%s%s"
		folder=$2
		identifier=$3
		args="${folder} ${identifier}"
		;;
	PREPARE)
		format="%s%s"
		identifier=$2
		args="${identifier}"
		;;
	START)
		format="%s%s"
		identifier=$2
		args="${identifier}"
		;;
	*)
		echo "command ${command} not found"
		exit 1
		;;
esac

${pomp_cmd} ${seq_num} ${format} ${command} ${args} 2>&1 | while read line; do
	if [ -n "$(echo ${line} | grep MSG)" ] &&
		[ -n "$(echo ${line} | grep ID:${seq_num})" ]
		then
			echo ${line}
		fi
done
